-- first delete all tables
DROP TABLE IF EXISTS guild_api_activations;
DROP TABLE IF EXISTS guild_presets;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS bot_roles;
DROP TABLE IF EXISTS guild_sessions;
DROP TABLE IF EXISTS guilds;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS scopes;
DROP TABLE IF EXISTS bot_presets;
DROP TABLE IF EXISTS chat_messages;